name: UI Tests
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Node dependencies
        run: npm ci || npm i
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start backend and run tests
        run: |
          python -m server.app &
          npx wait-on http://localhost:10000
          npx playwright test --reporter=list,html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
